name: release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          npm install
      - uses: ahwelgemoed/mendix-widget-build-action-monorepo@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          author_name: app-services-release-bot
          bot_commit_message: app-services-release
          bot_author_name: app-services-release-bot
          bot_author_email: app-services-release-bot@mendix.com
          commit_message_trigger: publish new Package
          packages_folder: packages
          identify_widgets_folders: -widgets
